service: cs4-gpt-plugin-poc01
app: app-gpt-plugin-v1

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-northeast-2
  environment:
    QUOTE_TABLE_NAME: cs4-gpt-plugin-poc01-quote
    TARIFF_TABLE_NAME: cs4-gpt-plugin-poc01-tariff
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/cs4-gpt-plugin-poc01-quote"

plugins:
  - serverless-offline
  - serverless-cloudfront-invalidate

custom:
  cloudfrontInvalidate:
    - distributionIdKey: "CloudFrontDistributionId"
      items:
        - "/.well-known/ai-plugin.json"

functions:
  get-quote:
    handler: src/quote.handler
    events:
      - http:
          path: quote
          method: post
          cors: true
    iam:
      role:
        statements:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
              - dynamodb:GetItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
              - dynamodb:Query
              - dynamodb:Scan
            Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/cs4-gpt-plugin-poc01-tariff"

resources:
  Resources:
    CS4GPTPluginBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: cs4-gpt-plugin-bucket
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref CS4GPTPluginBucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                CanonicalUser: !GetAtt CloudFrontOAI.S3CanonicalUserId
              Action: s3:GetObject
              Resource: !Sub "arn:aws:s3:::${CS4GPTPluginBucket}/*"
    CloudFrontOAI:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: OAI for cs4-gpt-plugin-bucket
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          Origins:
            - DomainName: !GetAtt
                - CS4GPTPluginBucket
                - DomainName
              Id: S3Origin
              S3OriginConfig:
                OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontOAI}
          DefaultRootObject: index.html
          DefaultCacheBehavior:
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: all
  Outputs:
    BucketName:
      Description: The name of the S3 bucket
      Value: !Ref CS4GPTPluginBucket
    CloudFrontDistributionId:
      Description: The ID of the CloudFront distribution
      Value: !Ref CloudFrontDistribution
